Exercise.destroy_all
User.destroy_all
Muscle.destroy_all
WorkoutLog.destroy_all
WorkoutSession.destroy_all


#User
User.create(username: "Bob", password_digest: "123456", weight: "240lb")

# Muscles

Muscle.create(name: "Abs", image: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app/2.1.2/img/guide-13.gif")
Muscle.create(name: "Arms", image: "https://i.pinimg.com/originals/2f/87/7b/2f877b8c7a26d0b472ed198b8681036a.gif")
Muscle.create(name: "Back", image: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app/2.1.2/img/guide-3.gif")
Muscle.create(name: "Calves", image: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app/2.1.2/img/guide-9.gif")
Muscle.create(name: "Chest", image: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app/2.1.2/img/guide-1.gif")
Muscle.create(name: "Legs", image: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app/2.1.2/img/guide-7.gif")

#Exercises

Exercise.create(name: "Plank", image: "https://i.gifer.com/Gg2G.mp4", desc: "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.", muscle_id: Muscle.first.id )

Exercise.create(name: "Elbow-to-knee crunch", image: "https://i.gifer.com/3xhG.gif", desc: "Lie on the floor, crossing your right leg across your bent left knee. Clasp your hands behind your head, beginning with your shoulder blades on the ground. This will be your starting position. Perform the motion by flexing the spine and rotating your torso to bring the left elbow to the right knee. Return to the starting position and repeat the movement for the desired number of repetitions before switching sides.", muscle_id: Muscle.first.id )

Exercise.create(name: "3/4 sit-up", image: "https://i.gifer.com/7BhQ.gif", desc: "Lie down on the floor and secure your feet. Your legs should be bent at the knees. Place your hands behind or to the side of your head. You will begin with your back on the ground. This will be your starting position. Flex your hips and spine to raise your torso toward your knees. At the top of the contraction your torso should be perpendicular to the ground. Reverse the motion, going only Â¾ of the way down. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.first.id )

Exercise.create(name: "Mountain climber", image: "https://i.gifer.com/7VtB.gif", desc: "Begin in a pushup position, with your weight supported by your hands and toes. Flexing the knee and hip, bring one leg until the knee is approximately under the hip. This will be your starting position. Explosively reverse the positions of your legs, extending the bent leg until the leg is straight and supported by the toe, and bringing the other foot up with the hip and knee flexed. Repeat in an alternating fashion for 20-30 seconds.", muscle_id: Muscle.first.id )

Exercise.create(name: "V-up", image: "https://i.gifer.com/UHt6.gif", desc: "Lie flat on the floor (or exercise mat) on your back with your arms extended straight back behind your head and your legs extended also. This will be your starting position. As you exhale, bend at the waist while simultaneously raising your legs and arms to meet in a jackknife position. Tip: The legs should be extended and lifted at approximately a 35-45 degree angle from the floor and the arms should be extended and parallel to your legs. The upper torso should be off the floor. While inhaling, lower your arms and legs back to the starting position. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.first.id )

Exercise.create(name: "Dumbbell Bicep Curl", image: "https://i.gifer.com/7hh1.gif", desc: "Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position. Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Then, inhale and slowly begin to lower the dumbbells back to the starting position. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.second.id )

Exercise.create(name: "Seated dumbbell shoulder press", image: "https://i.gifer.com/8c4C.gif", desc: "While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.
Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position. Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position. Now, exhale and push the dumbbells upward until they touch at the top. Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.second.id )

Exercise.create(name: "Triceps dip", image: "https://i.gifer.com/460w.gif", desc: "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars. Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm. Then, exhale and push your torso back up using your triceps to bring your body back to the starting position. Repeat the movement for the prescribed amount of repetitions.", muscle_id: Muscle.second.id )

Exercise.create(name: "Single-arm dumbbell triceps extension", image: "https://i.gifer.com/90Lm.gif", desc: "Grab a dumbbell and either sit on a military press bench or a utility bench that has a back support on it as you place the dumbbells upright on top of your thighs or stand up straight. Clean the dumbbell up to bring it to shoulder height and then extend the arm over your head so that the whole arm is perpendicular to the floor and next to your head. The dumbbell should be on top of you. The other hand can be kept fully extended to the side, by the waist, supporting the upper arm that has the dumbbell or grabbing a fixed surface. Rotate the wrist so that the palm of your hand is facing forward and the pinkie is facing the ceiling. This will be your starting position. Slowly lower the dumbbell behind your head as you hold the upper arm stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.Return to the starting position by flexing your triceps as you breathe out. Tip: It is imperative that only the forearm moves. The upper arm should remain at all times stationary next to your head. Repeat for the recommended amount of repetitions and switch arms.", muscle_id: Muscle.second.id )

Exercise.create(name: "Alternating incline dumbbell biceps curl", image: "https://i.gifer.com/IsBO.gif", desc: "Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.
While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second. Slowly begin to bring the dumbbells back to starting position as your breathe in. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.second.id )

Exercise.create(name: "Pullups", image: "https://www.nickhallbodytransformations.com/wp-content/uploads/2019/01/00171301-Assisted-Pull-up_Back_360.gif", desc: "Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched. Repeat this motion for the prescribed amount of repetitions.", muscle_id: Muscle.third.id )

Exercise.create(name: "Bent Over Barbell Row", image: "https://www.nickhallbodytransformations.com/wp-content/uploads/2019/01/02931301-Dumbbell-Bent-Over-Row_Back-FIX_360.gif", desc: "Holding a dumbbell in each hand bend at the waist to approximately a 45 degree angle with the palms of your hands facing each other. Have a slight bend in your knees. Row both dumbbells up to hip level squeezing your shoulder blades together. Return to the starting position.", muscle_id: Muscle.third.id )

Exercise.create(name: "Deadlift", image: "https://i.gifer.com/9QnD.gif", desc: "Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an over/under grip. With your feet and your grip set, take a big breath and then lower your hips and flex the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar. Lower the bar by bending at the hips and guiding it to the floor.", muscle_id: Muscle.third.id )

Exercise.create(name: "Seated Cable Rows", image: "https://c.tenor.com/iS3NQc2vHwIAAAAM/back-rows-james-smith.gif", desc: "For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked. Lean over as you keep the natural alignment of your back and grab the V-bar handles. With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise. Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.third.id )

Exercise.create(name: "Bent Over Row With Torsonator", image: "https://www.nickhallbodytransformations.com/wp-content/uploads/2019/01/05741301-Lever-Bent-over-Row-plate-loaded_Back_360.gif", desc: "Straddle the bar with your knees slightly bent. Bend forward at the waist until your torso is at a 45 degreee angle. Grip the bar close to the weight plates with both hands, using a neutral grip. One hand in front the other. Keeping your back straight and exhaling, pull the bar straight up by bending your elbows until the plates touch your chest. Hold and squeeze your back muscles. Return to the start position in a slow smooth movement to place emphasis on your lats. Inhale as you do so. Keep the bar from touching the floor. Pause then repeat.", muscle_id: Muscle.third.id )

Exercise.create(name: "Standing Calf Raises", image: "https://thumbs.gfycat.com/HarmfulIndelibleHarpyeagle-max-1mb.gif", desc: "Adjust the padded lever of the calf raise machine to fit your height. Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position. Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down. Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.
Repeat for the recommended amount of repetitions", muscle_id: Muscle.fourth.id )

Exercise.create(name: "Seated Calf Raise", image: "https://i2.wp.com/www.strengthlog.com/wp-content/uploads/2020/03/calf-raise-seated.gif?fit=600%2C600&ssl=1", desc: "Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter. Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward.
Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position. Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement. Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.fourth.id )

Exercise.create(name: "Calf Press On The Leg Press Machine", image: "https://i.pinimg.com/originals/66/1a/1e/661a1e8d41a913d99d1c4db47aa1cd0d.gif", desc: "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you without locking your knees. (Note: In some leg press units you can leave the safety bars on for increased safety. If your leg press unit allows for this, then this is the preferred method of performing the exercise.) Your torso and the legs should make perfect 90-degree angle. Now carefully place your toes and balls of your feet on the lower portion of the platform with the heels extending off. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position. Press on the platform by raising your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down. Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.
Repeat for the recommended amount of repetitions.", muscle_id: Muscle.fourth.id )

Exercise.create(name: "Pushups", image: "https://i.gifer.com/BfG6.gif", desc: "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.", muscle_id: Muscle.fifth.id )

Exercise.create(name: "Barbell Incline Bench Press", image: "https://i.gifer.com/MH2W.gif", desc: "Load the bar to an appropriate weight for your training. Lay on the bench with your feet flat on the ground, driving through to your hips. Your back should be arched, and your shoulder blades retracted. Take a medium, pronated grip covering the rings on the bar. Remove the bar from the rack, holding the weight above your chest with your arms extended. This will be your starting position. Lower the bar to the sternum by flexing the elbows. Maintain control and do not bounce the bar off of your chest. Your lats should stay tight and elbows slightly drawn in. After touching your torso with the bar, extend the elbows to return the bar to the starting position.", muscle_id: Muscle.fifth.id )

Exercise.create(name: "Cable Chest Press", image: "https://thumbs.gfycat.com/EasygoingKeyDwarfmongoose-size_restricted.gif", desc: "Adjust the weight to an appropriate amount and be seated, grasping the handles. Your upper arms should be about 45 degrees to the body, with your head and chest up. The elbows should be bent to about 90 degrees. This will be your starting position. Begin by extending through the elbow, pressing the handles together straight in front of you. Keep your shoulder blades retracted as you execute the movement. After pausing at full extension, return to th starting position, keeping tension on the cables. You can also execute this movement with your back off the pad, at an incline or decline, or alternate hands.", muscle_id: Muscle.fifth.id )

Exercise.create(name: "Incline Dumbbell Flyes", image: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-dumbbell-Fly.gif", desc: "Hold a dumbbell on each hand and lie on an incline bench that is set to an incline angle of no more than 30 degrees.
Extend your arms above you with a slight bend at the elbows. Now rotate the wrists so that the palms of your hands are facing you. Tip: The pinky fingers should be next to each other. This will be your starting position. As you breathe in, start to slowly lower the arms to the side while keeping the arms extended and while rotating the wrists until the palms of the hand are facing each other. Tip: At the end of the movement the arms will be by your side with the palms facing the ceiling. As you exhale start to bring the dumbbells back up to the starting position by reversing the motion and rotating the hands so that the pinky fingers are next to each other again. Tip: Keep in mind that the movement will only happen at the shoulder joint and at the wrist. There is no motion that happens at the elbow joint. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.fifth.id )

Exercise.create(name: "Decline Barbell Bench Press", image: "http://assets.menshealth.co.uk/main/assets/DeclineB.gif?mtime=1436203065", desc: "Lie back on a decline bench with the feet securely locked at the front of the bench. Using a wide, pronated (palms forward) grip that is around 3 inches away from shoulder width (for each hand), lift the bar from the rack and hold it straight over you with your arms locked. The bar will be perpendicular to the torso and the floor. This will be your starting position. As you breathe in, come down slowly until you feel the bar on your lower chest. After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up. Repeat the movement for the prescribed amount of repetitions.", muscle_id: Muscle.fifth.id )

Exercise.create(name: "Barbell Full Squat", image: "https://c.tenor.com/lIUdDtsYRxsAAAAC/high-bar.gif", desc: "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it. Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.Step away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times and maintain a straight back. This will be your starting position. Begin to slowly lower the bar by bending the knees and sitting back with your hips as you maintain a straight posture with the head up. Continue down until your hamstrings are on your calves. Inhale as you perform this portion of the movement. Begin to raise the bar as you exhale by pushing the floor with the heel or middle of your foot as you straighten the legs and extend the hips to go back to the starting position.Repeat for the recommended amount of repetitions.", muscle_id: Muscle.find_by(name: "Legs").id)

Exercise.create(name: "Forward lunge", image: "https://i0.wp.com/post.greatist.com/wp-content/uploads/sites/2/2019/05/PERFECT-SERIES_LUNGE-HORIZONTAL_GRAIN.gif?w=1155&h=812", desc: "Stand erect with your feet hip-width apart, chest out, and shoulders back, maintaining the natural curvature of your spine. Your knees should be unlocked and your hand on your hips. This is your starting position.
Take a moderate-length step forward with one foot, descending to a point in which your rear knee approaches the floor without touching, maintaining your body's upright posture. Your front knee should bend about 90 degrees, but for knee health it should not be forward of the vertical plane that extends straight up from your toes. If so, take a slightly longer step.From the bottom position, push back up from your forward foot, bringing it back beside the other.Repeat on the opposite side for the required number of repetitions.", muscle_id: Muscle.find_by(name: "Legs").id)

Exercise.create(name: "Leg Press", image: "https://jeremystraining.com/wp-content/uploads/2019/12/leg-press.gif", desc: "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position. As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle. Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale. Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.", muscle_id: Muscle.find_by(name: "Legs").id)

Exercise.create(name: "Leg Extensions", image: "https://www.technogym.com/wpress/wp-content/uploads/2019/04/leg-extension-gif.gif", desc: "For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position. Tip: You will need to adjust the pad so that it falls on top of your lower leg (just above your feet). Also, make sure that your legs form a 90-degree angle between the lower and upper leg. If the angle is less than 90-degrees then that means the knee is over the toes which in turn creates undue stress at the knee joint. If the machine is designed that way, either look for another machine or just make sure that when you start executing the exercise you stop going down once you hit the 90-degree angle. Using your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position. Slowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit. Repeat for the recommended amount of times.", muscle_id: Muscle.find_by(name: "Legs").id)

Exercise.create(name: "Lying Leg Curls", image: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif", desc: "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment. Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.
As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second. As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions.", muscle_id: Muscle.find_by(name: "Legs").id)

#WorkoutSession

WorkoutSession.create(title: "Abs Workout", weekday: "Monday", user_id: User.first.id)

#WorkoutLog

WorkoutLog.create(set: 4, rep: 12, note: "25lbs. feels easy, needs to put more weight next time.", workout_session_id: WorkoutSession.first.id, exercise_id: Exercise.first.id )

WorkoutLog.create(set: 4, rep: 12, note: "25lbs. feels easy, needs to put more weight next time.", workout_session_id: WorkoutSession.first.id, exercise_id: Exercise.second.id )

WorkoutLog.create(set: 4, rep: 12, note: "25lbs. feels easy, needs to put more weight next time.", workout_session_id: WorkoutSession.first.id, exercise_id: Exercise.third.id )

WorkoutLog.create(set: 4, rep: 12, note: "25lbs. feels easy, needs to put more weight next time.", workout_session_id: WorkoutSession.first.id, exercise_id: Exercise.fourth.id )

WorkoutLog.create(set: 4, rep: 12, note: "25lbs. feels easy, needs to put more weight next time.", workout_session_id: WorkoutSession.first.id, exercise_id: Exercise.fifth.id )


puts "✅ Done seeding!"
